### ISSUE TITLE
Improve readability for pointer operations in C

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1148]
**Describe the bug**
Currently pointers are dereferenced whenever they are used in C.
E.g:
```python
def f(x : 'int[:]' = None):
    if x is not None:
        print(x.shape[0])
```
is translated to:
```c
void f(t_ndarray *x)
{
    if (x != NULL)
    {
        printf("%ld\n", (*x).shape[0]);
    }
}
```
This is easy to implement as `_print_Variable` takes care of the dereferencing internally.
However it is not the standard way of handling pointers in C. As a result it is a bit harder to parse. We would prefer the following syntax:
```c
void f(t_ndarray *x)
{
    if (x != NULL)
    {
        printf("%ld\n", x->shape[0]);
    }
}
```

**Language**
C

**Tasks**
- [x] Modify `VariableAddress` so it becomes `ObjectAddress`
    This means we can obtain the address of any object, not just a variable (e.g. the result of a FunctionCall)
    Potential pitfall : Address of address (this may be used in the cwrapper)
    - [x] Rename everywhere necessary
    - [x] Update the restrictions in `__init__`
    - [x] Consider moving this class to a different file
    - [x] Update the printer
- [x] Locate all functions which access class elements
- [x] Update the functions to store the base in an `ObjectAddress` before printing
    Potential pitfall : `DottedVariable` contains 2 objects which may be pointers and need to be referenced accordingly

**Comment by EmilyBourne** [comment]
> I need to know if `FunctionAddress` requires the same changes?

What changes exactly are you referring to? You can't do pointer operations on a function address
