### ISSUE TITLE
NumPy number classification functions

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1425]
## Relevant Discussion

https://github.com/pyccel/pyccel/discussions/1408
cc: @dominikbell

## Describe the feature
Several of NumPy's functions number classification functions are not supported. We would like to add support for the most common of these. Namely:
- `isnan`
- `isinf`
- `isfinite`

### In C:
Implementations of these functions exist in the standard header `math.h` (see pages 216-217 of the [c99 standard](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf))

### In Fortran
Implementations of these functions exist in the `ieee_arithmetic` intrinsic module (see [here](https://fortranwiki.org/fortran/show/ieee_arithmetic) for details)

## Tasks

- [ ] Create classes in `numpyext.py` for each of the three functions
- [ ] Add the functions to the [list of numpy functions](https://github.com/pyccel/pyccel/blob/devel/pyccel/ast/numpyext.py#L1745)
- [ ] Add print functions in C ensuring that the necessary header is imported
- [ ] Add print functions in Fortran ensuring that the necessary module is imported
- [ ] If necessary, add print functions in Python

**Comment by neet-14** [comment]
I am interested to work on this issue. Can you provide some guidance and assistance in resolving this.

**Comment by EmilyBourne** [comment]
> I am interested to work on this issue. Can you provide some guidance and assistance in resolving this.

Hello! Thanks for your interest in Pyccel. It's always useful to have extra help :)

If you haven't already, I'd suggest starting with the [developer docs](https://github.com/pyccel/pyccel/tree/devel/developer_docs). You also need to make sure you've installed a version of Pyccel from source in [editable mode](https://github.com/pyccel/pyccel#from-sources).

For this issue you need to start by creating classes in pyccel/ast/numpyext.py to describe the missing functions. You should be able to use something like `pyccel.ast.numpyext.NumpySin` as an example.

The syntactic and semantic stages should take care of themselves, but you will need to add printing functions for some languages (certainly for Fortran, C and Python may take care of themselves thanks to the class inheritance). You can find more information about the printing stage in the [docs](https://github.com/pyccel/pyccel/blob/devel/developer_docs/codegen_stage.md).

Don't hesitate to join our [discord](https://discord.gg/2Q6hwjfFVb) so you can ask me or the pyccel-dev team questions directly.
Let me know if you need any more information/help to get started.

Thanks again :)

**Comment by EmilyBourne** [comment]
These functions are implemented for the math and cmath libraries. This should make it easy to add the printer
