### ISSUE TITLE
Tuples

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1566]
The current implementation of tuples is not satisfactory for 3 main reasons:
1. Tuples as arguments/results are not handled
2. Tuples are stored in `TupleVariable` classes which make them incompatible with classes
3. Tuples are handled as a special case, but lots of things needed for tuples will also be needed for other containers (sets, maps, lists).

In order to fix the 2nd and 3rd problems, tuples should be treated using class notation. This should be straightforward for `HomogeneousTupleVariable`s but is non-trivial for `InhomogeneousTupleVariable`s.

The tasks are therefore:
- [ ] Use class notation for tuples
- [ ] Add support for tuples as arguments
     - [ ] #1519
     - [ ] #738
- [ ] Add support for tuples as results
     - [ ] #1321
     - [ ] #337

### Related issues:
- #1392
- #1182
