### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1567]
Support for homogeneous lists would be a great improvement to Pyccel. This epic summarises the issues which must be completed to implement this:

- [ ] Add syntactic and semantic parser support for lists #1529
- [ ] Add Python printing of lists #1529 
- [ ] Add Fortran printing of lists
- [ ] Add C printing of lists
- [ ] Allow lists as function arguments
- [ ] Allow lists as function results
- [ ] Add documentation explaining the implementation and why non-homogeneous lists will never be implemented
