### ISSUE TITLE
Sets

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1569]
Support for sets would be a great improvement to Pyccel. This epic summarises the issues which must be completed to implement this:

- [ ] Add syntactic and semantic parser support for sets #1529
- [ ] Add Python printing of sets #1529 
- [ ] Add Fortran printing of sets
- [ ] Add C printing of sets
- [ ] Allow sets as function arguments
- [ ] Allow sets as function results
- [ ] Add documentation explaining the implementation
