### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1570]
Support for maps would be a great improvement to Pyccel. This epic summarises the issues which must be completed to implement this:

- [ ] Add syntactic and semantic parser support for maps
- [ ] Add Python printing of maps
- [ ] Add Fortran printing of maps
- [ ] Add C printing of maps
- [ ] Allow maps as function arguments
- [ ] Allow maps as function results
- [ ] Add documentation explaining the implementation
