### ISSUE TITLE
Current Fortran extension imposes several restrictions

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#370]
There are several issues with f2py. Especially when trying to use booleans or worse boolean arrays. We should move to using CPython.

#### Current problems with f2py (ticked options now work)
- [x] Cannot have optional arguments (ie pass None)
- [x] Bool array incompatibility with numpy
  errors such as: `failed to initialize intent(inout) array -- input '?' not compatible to 'b'`
- [x] Interfaces don't work. Our current approach to f2py does not allow for interfaces (see Issue #301)
- [ ] Can't return a tuple and another object (see issue #340)
- [ ] Can't return an array of unknown size
- [x] Can't use capitalised name to access fortran function (see issue #227)
- [x] Can't return a bool

**Comment by EmilyBourne** [comment]
f2py has unusual behaviour when combining optional arguments and arrays.
The following function:
```
@types('real[:]','int')
def test(x, opt=1):
    print(x, opt)
```
leads to a function with docstring:
```
test(x,[n0_x,opt])

Wrapper for ``test``.

Parameters
----------
x : input rank-1 array('d') with bounds (n0_x)

Other Parameters
----------------
n0_x : input int, optional
    Default: len(x)
opt : input long, optional
    Default: 1
```
As a result specifying `opt` without specifying `n0_x` can only be done correctly if it is specified with a keyword.

So the following test fails:
```
import numpy as np
from pyccel.decorators import types
from pyccel.epyccel import epyccel

@types('real[:]','int')
def test(x, opt=1):
    return opt

test2 = epyccel(test)

y = np.ones(4)

assert(test(y,2) == test2(y, 2))
```
while this passes:
```
import numpy as np
from pyccel.decorators import types
from pyccel.epyccel import epyccel

@types('real[:]','int')
def test(x, opt=1):
    return opt

test2 = epyccel(test)

y = np.ones(4)

assert(test(y,2) == test2(y, opt = 2))
```

**Comment by EmilyBourne** [comment]
See point 9 at https://stackoverflow.com/tags/fortran-iso-c-binding/info for an example of calling fortran from c. This example includes how to return allocated arrays

**Comment by yguclu** [comment]
We can close this issue as we do not use f2py anymore and we have dedicated issues for the unchecked boxes in the description.
