### ISSUE TITLE
Remove unnecessary sympy inheritance

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#665]
For historic reasons all classes in pyccel's ast inherit from sympy objects. This has now become more of a hindrance than a help, so we would like to remove this.

To do so we must do the following:
- [x] Remove the use of sympy objects (Function #656, Tuple #657, Indexed #658, Symbol #716, others? #663)
- [x] Use mutable objects in classes instead of the opaque sympy attribute `_args`
- [x] Add helper functions to pyccel Basic class (atomic, subs, etc). See #694
- [x] Remove sympify calls in the code. See #686
- [x] Remove inheritance from sympy objects. See #661 and #662

Once this has been done the following improvements can be made to pyccel:
- [x] All classes should have a `__str__` method. Often this will replace the `_sympystr` method. See #666
- [x] Classes can have `__slots__` to improve performance. See #515

In addition sympy inheritance can be removed elsewhere:
- [x] In the codegen printers. See #746

**Comment by EmilyBourne** [comment]
It may also be useful to remove `Symbol` and replace it with our own class for which we can implement magic methods for comparison etc. This will avoid the 1000s of str casts. In addition, we do not use any of the properties of `Symbol`. We are just using it as a wrapper around a string. Perhaps a string would be sufficient?
